version: "3"
services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Express
    ports:
      - 1433:1433
  api:
    image: controllerbase/misty:red
    ports:
      - 80:5000
    depends_on:
      - db
